# Generated by Django 5.1.1 on 2024-09-16 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bids_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='image',
        ),
        migrations.AddField(
            model_name='auctions',
            name='url_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
